language: python
branches:
  only:
    - master
    - development

addons:
  apt:
    packages:
      - python-apt
      - python3-apt

matrix:
  include:
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7

before_install:
  - pip install tox

script:
  - tox
